baseURL: https://thomasgf-portfolio2021.netlify.app/
languageCode: en-us
title: T.G.F.
theme: forty
googleAnalytics: ''
disqusShortname: ''

menu:
 # main: 
 #   - URL : about
  #    name : About
 #     weight : 1
 #   - URL : blogs
 #     name : Blog
 #     weight : 2
 #   - URL : posts
 #     name : Posts
 #     weight : 3
 #   - URL : contact 
#      name : contact
 #     weight : 4

params:
  theme_color : #ff8c00
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my portfolio website ! You can discover more about who I am and my work below.
    title: Hi, my name is Thomas
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    enable: true
    formEmail: thomasg.mam2022@london.edu
    email:
      - email: thomasg.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +225 07 79 69 15 74
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
     #   label: Twitter
     #   url: https://www.twitter.com
      #- icon: fa-facebook
      #  label: Facebook
      #  url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/thomasgiannetti
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/thomasgiannetti
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/thomas-giannetti
        
  image: ''
  name: Your name
  navigation:
    #button1:
    #  - name: Home
    #     url: homepage
    #button2:
     # - name: Log In
     #   url: '#'
    links:
      - name: Home
        url: '#'
      - name: Portfolio
        url: portfolio
      - name: About Me
        url: about/who_am_i
      - name: CV
        url: cv/cv_tgf
#    menu: Menu
    
    title: T.G.F.
  tiles:
    enable: yes
    showcase:
      - image: im01.jpg
        subtitle: Short biography
        title: About Me
        url: /about/who_am_i
      - image: im02.jpg
        subtitle: Examples of my work
        title: Work
        url: portfolio
      - image: im03.jpg
        subtitle: My resumé
        title: CV
        url: /cv/cv_tgf
      - image: im09.jpg
        subtitle: Additional Information About Me
        title: Fun Fact
        url: fun_fact/fun_fact
    
  #two:
  #  buttonText: Get Started
  #  enable: yes
  #  subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
  #    \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
  #    condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
  #    pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
  #    Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
  #    amet pharetra et feugiat tempus."
  #  title: Massa libero
  #  url: blogs
